replicaCount: 1

image:
  repository: ezrxcrnpd.azurecr.io/ezrx-backend/analytics-api
  pullPolicy: Always
  tag: d3d0b5254bd78bfd09bd61f5c0f2d2f1c5486d6f


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP


ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    host: analytics-api-uat.ezrx.com
    path: /
  tls:
    enabled: true
    secretName: ingress-tls

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}


env:
  config:
    #ROLES [username,salesorg,customer/shpldto,shipto]
    APPLICATION_INSIGHTS_KEY: 791227d8-607e-4ee2-9b56-f56469cdb50a
    Client_Admin: "1111"
    Client_User: "1111"
    ENABLE_LOGGING: "false"
    ENABLE_PUB_SUB: "true"
    ERETURN_ENGINE_URL: http://ereturns-api-svc:7090/query
    External_Sales_Rep: "0120"
    HANA_MAX_CONNECTION_LIFETIME: 2
    HANA_MAX_IDLE_CONNECTION: 2
    HANA_MAX_OPEN_CONNECTION: 30
    HANA_SCHEMA: ECT_RSD_BHQ
    Internal_Sales_Rep: "0120"
    LICENSE_ENGINE_GRAPHQL: http://license-api-svc:7091/query
    LOG_ENGINE_GRAPHQL: http://log-api-svc:7095/query
    LOG_LEVEL: ERROR
    MASK_ERROR: "true"
    NATS_CONNECT_URL: nats://nats-api-svc:4222
    ORDER_ENGINE_GRAPHQL: http://order-api-svc:7093/query
    PORT: 7094
    POSTGRES_DBNAME: citus
    POSTGRES_HOST: 10.3.1.20
    POSTGRES_MAX_CONNECTION_LIFETIME: 2
    POSTGRES_MAX_IDLE_CONNECTION: 15
    POSTGRES_MAX_OPEN_CONNECTION: 15
    POSTGRES_PORT: 2432
    POSTGRES_SSLMODE: disable
    ROOT_Admin: "0000"
    TZ: Asia/Singapore
    ZP_Admin: "0100"
  secret:
    AUTH_TOKEN: dzl4cEFhQkRZUQ==
    HANA_URL: aGRiOi8vWlBfZVpSeDI6WlBlWlJ4MiFAMTAuMTAuNS43OjM2MDQx
    POSTGRES_PWD: WnVlbGxpZzAyIQ==
    POSTGRES_USER: ZXpyeHVhdHdlYg==
    SECRET: NzliYTI4MzItOGE3YS00ZGU2LWE2ZjktMGViNzEzZGIzMTRk