apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  namespace: {{ .Release.Namespace }}
data:
    {{- range $key, $val := .Values.env.config }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}