apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=ezrx
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "value": "true", "key": "UserWorkload", "effect": "NoSchedule"}]'
  labels:
    kubernetes.io/metadata.name: ProjectA
  name: ezrx
spec:
  finalizers:
  - kubernetes
